/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controladorproductos;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author giool
 */
public class Listaproducto extends javax.swing.JFrame {
    fondopanel fondo= new fondopanel();
private ImageIcon imagen;
private Icon icono;
    /**
     * Creates new form Listaproducto
     */
    public Listaproducto() {
           this.setContentPane(fondo);
        initComponents();
         this.setLocationRelativeTo(this);
        //declarar la foto
        this.imagenicono(this.lbl_iconolista, "src/vista/pngcompu.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_iconolista = new javax.swing.JLabel();
        btn_todoslosproductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_producto = new javax.swing.JTable();
        btn_filtrar = new javax.swing.JButton();
        btn_volvermenu = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_todoslosproductos.setFont(new java.awt.Font("Gadugi", 2, 12)); // NOI18N
        btn_todoslosproductos.setText("TODOS LOS PRODUCTOS");
        btn_todoslosproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todoslosproductosActionPerformed(evt);
            }
        });

        tbl_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Stock minimo", "Stock actual", "precio", "objeto tecnologico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_producto);

        btn_filtrar.setText("OCULTAR PRODUCTOS");
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });

        btn_volvermenu.setText("VOLVER AL MENU");
        btn_volvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volvermenuActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_iconolista, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_todoslosproductos)
                .addGap(40, 40, 40)
                .addComponent(btn_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_volvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_iconolista, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(btn_volvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_todoslosproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_todoslosproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todoslosproductosActionPerformed
         Controladorproductos cl = new Controladorproductos();
       ArrayList<Producto> misproductos = cl.traerProducto();
       //obtener el modelo de la tabla
       DefaultTableModel modeloTabla = (DefaultTableModel) tbl_producto.getModel();

       //Dejamos el modelo sin registros
       modeloTabla.setRowCount(0);
       
       for(Producto pro : misproductos)
       {
           int codigo = pro.getCodigo();
           String descripcion = pro.getDescripcion();
           int precio = pro.getPrecio();
           int stock_min=pro.getStock_minimo();
           int stock_act =pro.getStock_actual();
           String tipo_producto=pro.getObjeto_teconologico();
           
           
           //crear registro del arraylist a la tabla 
           modeloTabla.addRow(new Object[]{codigo, descripcion, precio, stock_min, stock_act, tipo_producto});
        }

        
                                      
    }//GEN-LAST:event_btn_todoslosproductosActionPerformed

    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
       Controladorproductos cl = new Controladorproductos();
       ArrayList<Producto> misProductos = cl.filtrarPorStock();
       //obtener el modelo de la tabla
       DefaultTableModel modeloTabla = (DefaultTableModel) tbl_producto.getModel();

       //Dejamos el modelo sin registros
       modeloTabla.setRowCount(0);
       
       for(Producto pro : misProductos)
       {
           int codigo = pro.getCodigo();
           String descripcion = pro.getDescripcion();
           int precio = pro.getPrecio();
           int stock_min=pro.getStock_minimo();
           int stock_act =pro.getStock_actual();
           String tipo_producto=pro.getObjeto_teconologico();
           
           
           //crear registro del arraylist a la tabla 
           modeloTabla.addRow(new Object[]{codigo, descripcion, precio, stock_min, stock_act, tipo_producto});
        }
    }//GEN-LAST:event_btn_filtrarActionPerformed

    private void btn_volvermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volvermenuActionPerformed
        Menu menu=new Menu();
          
          menu.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btn_volvermenuActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listaproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listaproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listaproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listaproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listaproducto().setVisible(true);
            }
        });
    }
     private void imagenicono(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_todoslosproductos;
    private javax.swing.JButton btn_volvermenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_iconolista;
    private javax.swing.JTable tbl_producto;
    // End of variables declaration//GEN-END:variables

class fondopanel extends JPanel
    {
        private Image fondoimagen;
        
        @Override
        public void paint(Graphics g)
        {
            fondoimagen = new ImageIcon(getClass().getResource("/imagen/fondodegradado.jpg")).getImage();
            
            g.drawImage(fondoimagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }


}
