/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controladorusuario;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;

/**
 *
 * @author giool
 */
public class Login extends javax.swing.JFrame {
     fondopanel fondo= new fondopanel();
     private ImageIcon imagen;
     private Icon icono;

    /**
     * Creates new form Login
     */
    public Login() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(this);
        //declarar la foto
        this.imagenicono(this.lbl_iconologin, "src/vista/iconologinpng.png");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulologin = new javax.swing.JLabel();
        lbl_iconologin = new javax.swing.JLabel();
        lbl_nombre_usulog = new javax.swing.JLabel();
        lbl_contraseñalog = new javax.swing.JLabel();
        txt_nombre_usulog = new javax.swing.JTextField();
        lbl_bienvenidolog = new javax.swing.JLabel();
        btn_iniciarsesion = new javax.swing.JButton();
        btn_loginvolver = new javax.swing.JButton();
        txt_contraseñalog = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_titulologin.setFont(new java.awt.Font("Impact", 3, 36)); // NOI18N
        lbl_titulologin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulologin.setText("INICIO DE SESIÓN");

        lbl_nombre_usulog.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        lbl_nombre_usulog.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_usulog.setText("nombre de usuario:");

        lbl_contraseñalog.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        lbl_contraseñalog.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contraseñalog.setText("Contraseña:");

        txt_nombre_usulog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_usulogActionPerformed(evt);
            }
        });

        lbl_bienvenidolog.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lbl_bienvenidolog.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bienvenidolog.setText("BIENVENIDO");

        btn_iniciarsesion.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        btn_iniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        btn_iniciarsesion.setText("Iniciar Sesión");
        btn_iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarsesionActionPerformed(evt);
            }
        });

        btn_loginvolver.setText("volver");
        btn_loginvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginvolverActionPerformed(evt);
            }
        });

        txt_contraseñalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lbl_nombre_usulog))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(lbl_contraseñalog)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_contraseñalog, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre_usulog, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_iconologin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lbl_bienvenidolog, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(lbl_titulologin, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btn_loginvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btn_iniciarsesion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulologin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_loginvolver))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbl_bienvenidolog, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_iconologin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_usulog, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre_usulog))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraseñalog)
                    .addComponent(txt_contraseñalog, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_iniciarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarsesionActionPerformed
        // TODO add your handling code here:
        Controladorusuario cu = new Controladorusuario();
        String nombre_usuario =txt_nombre_usulog .getText();
        String contraseña = txt_contraseñalog.getText();
        if(txt_nombre_usulog.getText().equals("")||txt_contraseñalog.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar sus datos primero");
            txt_nombre_usulog.requestFocus();    
        }else{
         Controladorusuario cl = new Controladorusuario();
         
         Usuario usuario =  cl.buscarUsuario(nombre_usuario,contraseña);
       
         if(usuario.getId_usuario()!= 0)
        {
         JOptionPane.showMessageDialog(this, "cuenta valida");
         Productovista prod = new Productovista();
          prod.setVisible(true);
          this.dispose();
          
          
       
       }else{
             JOptionPane.showMessageDialog(this,"usuario o contraseña no validos");
             txt_nombre_usulog.requestFocus();
             JOptionPane.showMessageDialog(this,"cuenta no valida");
             
         }
        }
        
    }//GEN-LAST:event_btn_iniciarsesionActionPerformed

    private void btn_loginvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginvolverActionPerformed
       Menu menulog = new Menu();
       menulog.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_loginvolverActionPerformed

    private void txt_nombre_usulogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_usulogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_usulogActionPerformed

    private void txt_contraseñalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñalogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
     private void imagenicono(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciarsesion;
    private javax.swing.JButton btn_loginvolver;
    private javax.swing.JLabel lbl_bienvenidolog;
    private javax.swing.JLabel lbl_contraseñalog;
    private javax.swing.JLabel lbl_iconologin;
    private javax.swing.JLabel lbl_nombre_usulog;
    private javax.swing.JLabel lbl_titulologin;
    private javax.swing.JPasswordField txt_contraseñalog;
    private javax.swing.JTextField txt_nombre_usulog;
    // End of variables declaration//GEN-END:variables

class fondopanel extends JPanel
    {
        private Image fondoimagen;
        
        @Override
        public void paint(Graphics g)
        {
            fondoimagen = new ImageIcon(getClass().getResource("/imagen/fondologin.jpg")).getImage();
            
            g.drawImage(fondoimagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }


}
