/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author giool
 */
public class Menu extends javax.swing.JFrame {
    fondopanel fondo= new fondopanel();
    private ImageIcon imagen;
private Icon icono;

    /**
     * Creates new form Menu
     */
    public Menu() {
         this.setContentPane(fondo);
        initComponents();
        
        //importante para la foto
        this.setLocationRelativeTo(this);
        //declarar la foto
        this.imagenicono(this.lbl_icono, "src/vista/pngcompu.png");
         this.imagenicono(this.lbl_fotosantiago, "src/vista/santiagofoto.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_icono = new javax.swing.JLabel();
        lbl_textoargumentativo1 = new javax.swing.JLabel();
        lbl_textoargumentativo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_textoargumentativo3 = new javax.swing.JLabel();
        lbl_fotosantiago = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_registro = new javax.swing.JMenuItem();
        mni_login = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mni_salir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mni_productos = new javax.swing.JMenuItem();
        mni_listaproductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("BIENVENIDO A COMPUTIZADOS.");
        lbl_titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        lbl_textoargumentativo1.setFont(new java.awt.Font("Dubai Medium", 2, 18)); // NOI18N
        lbl_textoargumentativo1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_textoargumentativo1.setText("¡La mejor tienda tecnologica de Santiago!");

        lbl_textoargumentativo2.setFont(new java.awt.Font("Dubai Medium", 2, 18)); // NOI18N
        lbl_textoargumentativo2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_textoargumentativo2.setText("¡Los mejores computadores");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dispositivos celulares");

        lbl_textoargumentativo3.setFont(new java.awt.Font("Dubai Medium", 2, 18)); // NOI18N
        lbl_textoargumentativo3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_textoargumentativo3.setText("Y  consolas de ultima generación!");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Registrar/Login");

        mni_registro.setText("Registro");
        mni_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_registroActionPerformed(evt);
            }
        });
        jMenu1.add(mni_registro);

        mni_login.setText("Login");
        mni_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mni_login);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        mni_salir.setText("Salir");
        mni_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_salirActionPerformed(evt);
            }
        });
        jMenu2.add(mni_salir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");

        mni_productos.setText("Productos");
        mni_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_productosActionPerformed(evt);
            }
        });
        jMenu3.add(mni_productos);

        mni_listaproductos.setText("Lista de productos");
        mni_listaproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_listaproductosActionPerformed(evt);
            }
        });
        jMenu3.add(mni_listaproductos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_textoargumentativo1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_textoargumentativo3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fotosantiago, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_textoargumentativo2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lbl_textoargumentativo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_textoargumentativo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(lbl_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_textoargumentativo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fotosantiago, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_registroActionPerformed
     Registro reg = new Registro();
     
     reg.setVisible(true);
    }//GEN-LAST:event_mni_registroActionPerformed

    private void mni_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_loginActionPerformed
      Login log = new Login();
      log.setVisible(true);
    }//GEN-LAST:event_mni_loginActionPerformed

    private void mni_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mni_salirActionPerformed

    private void mni_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_productosActionPerformed
       Productovista prod = new Productovista();
       prod.setVisible(true);
    }//GEN-LAST:event_mni_productosActionPerformed

    private void mni_listaproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_listaproductosActionPerformed
       Listaproducto listpro = new Listaproducto();
       listpro.setVisible(true);
    }//GEN-LAST:event_mni_listaproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private void imagenicono(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}
    
      private void imagenicono2(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_fotosantiago;
    private javax.swing.JLabel lbl_icono;
    private javax.swing.JLabel lbl_textoargumentativo1;
    private javax.swing.JLabel lbl_textoargumentativo2;
    private javax.swing.JLabel lbl_textoargumentativo3;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JMenuItem mni_listaproductos;
    private javax.swing.JMenuItem mni_login;
    private javax.swing.JMenuItem mni_productos;
    private javax.swing.JMenuItem mni_registro;
    private javax.swing.JMenuItem mni_salir;
    // End of variables declaration//GEN-END:variables

 //fondo de pantalla
    class fondopanel extends JPanel
    {
        private Image fondoimagen;
        
        @Override
        public void paint(Graphics g)
        {
            fondoimagen = new ImageIcon(getClass().getResource("/imagen/fondootecnologia.jpg")).getImage();
            
            g.drawImage(fondoimagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
