/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controladorproductos;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import controlador.Controladorusuario;
import javax.swing.JOptionPane;
import modelo.Producto;
/**
 *
 * @author giool
 */
public class Productovista extends javax.swing.JFrame {
    fondopanel fondo= new fondopanel();
    private ImageIcon imagen;
private Icon icono;

    /**
     * Creates new form Productovista
     */
    public Productovista() {
        this.setContentPane(fondo);
        initComponents();
         this.setLocationRelativeTo(this);
        //declarar la foto
        this.imagenicono(this.lbl_iconocomputizado, "src/vista/pngcompu.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_codigoprod = new javax.swing.JLabel();
        txt_codigoventa = new javax.swing.JTextField();
        lbl_cantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_realizarventa = new javax.swing.JButton();
        lbl_stockmin = new javax.swing.JLabel();
        txt_stockmin = new javax.swing.JTextField();
        lbl_stockact = new javax.swing.JLabel();
        txt_stockact = new javax.swing.JTextField();
        lbl_objtecn = new javax.swing.JLabel();
        txt_objtecno = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_iconocomputizado = new javax.swing.JLabel();
        lbl_tituloprod = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        lbl_descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        lbl_precioventa = new javax.swing.JLabel();
        txt_precio2 = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        btn_agregarprod = new javax.swing.JButton();
        btn_actualizarprod = new javax.swing.JButton();
        btn_eliminarprod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_codigoprod.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_codigoprod.setForeground(new java.awt.Color(255, 255, 255));
        lbl_codigoprod.setText("Ingrese codigo del producto:");

        lbl_cantidad.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad.setText("Ingrese la cantidad:");

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        btn_realizarventa.setText("Realizar venta");
        btn_realizarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_realizarventaActionPerformed(evt);
            }
        });

        lbl_stockmin.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_stockmin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_stockmin.setText("Stock minimo:");

        lbl_stockact.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_stockact.setForeground(new java.awt.Color(255, 255, 255));
        lbl_stockact.setText("Stock actual:");

        lbl_objtecn.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_objtecn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_objtecn.setText("Objeto tecnologico:");

        txt_objtecno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_objtecnoActionPerformed(evt);
            }
        });

        lbl_codigo.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_codigo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_codigo.setText("Codigo:");

        lbl_tituloprod.setFont(new java.awt.Font("Dubai Medium", 3, 24)); // NOI18N
        lbl_tituloprod.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloprod.setText("COMPUTIZADOS");

        btn_consultar.setForeground(new java.awt.Color(0, 0, 0));
        btn_consultar.setText("CONSULTAR PRODUCTOS");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_salir.setForeground(new java.awt.Color(0, 0, 0));
        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lbl_descripcion.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descripcion.setText("Descripcion del producto:");

        lbl_precioventa.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_precioventa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_precioventa.setText("Precio de venta:");

        lbl_total.setFont(new java.awt.Font("Javanese Text", 3, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setText("TOTAL: $");

        btn_agregarprod.setText("Agregar producto");
        btn_agregarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarprodActionPerformed(evt);
            }
        });

        btn_actualizarprod.setText("Actualizar producto");
        btn_actualizarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarprodActionPerformed(evt);
            }
        });

        btn_eliminarprod.setText("Eliminar producto");
        btn_eliminarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_iconocomputizado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tituloprod)
                .addGap(36, 36, 36)
                .addComponent(btn_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregarprod)
                        .addGap(100, 100, 100)
                        .addComponent(btn_actualizarprod)
                        .addGap(136, 136, 136)
                        .addComponent(btn_eliminarprod)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_objtecn)
                                        .addGap(63, 63, 63)
                                        .addComponent(lbl_codigo))
                                    .addComponent(txt_stockact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_stockact)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txt_stockmin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_stockmin)
                                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_descripcion)
                                    .addComponent(lbl_precioventa)
                                    .addComponent(txt_precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_objtecno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cantidad)
                                    .addComponent(txt_codigoventa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 127, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_total)
                                        .addGap(223, 223, 223))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_codigoprod)
                                        .addGap(119, 119, 119))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_realizarventa)
                                        .addGap(181, 181, 181))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_iconocomputizado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tituloprod)
                            .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion)
                    .addComponent(lbl_total))
                .addGap(18, 18, 18)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_precioventa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_precio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_stockmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_stockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_stockact)
                            .addComponent(btn_realizarventa))
                        .addGap(18, 18, 18)
                        .addComponent(txt_stockact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_objtecn)
                            .addComponent(lbl_codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_objtecno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregarprod)
                            .addComponent(btn_actualizarprod)
                            .addComponent(btn_eliminarprod))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_codigoprod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigoventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void btn_realizarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_realizarventaActionPerformed
        if(txt_codigoventa.getText().equals("")||txt_cantidad.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Primero debe ingresar la informacion");
            txt_codigoventa.requestFocus();
        }

        Controladorproductos cp = new Controladorproductos();
        double total;
        int codigo = Integer.parseInt(txt_codigoventa.getText());
        int cantidad = Integer.parseInt(txt_cantidad.getText());

        cp.vender_producto(codigo,cantidad);

        if(codigo==1){
            JOptionPane.showMessageDialog(this,"el producto celular tiene un 5% de descuento");
        }
        if(codigo==2){
            JOptionPane.showMessageDialog(this,"el producto computador tiene un 7% de descuento");
        }
        if(codigo==3){
            JOptionPane.showMessageDialog(this,"el producto consola tiene un 8% de descuento");
        }
        total=cp.calcular_venta(codigo, cantidad);

        lbl_total.setText(""+total);
    }//GEN-LAST:event_btn_realizarventaActionPerformed

    private void txt_objtecnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_objtecnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_objtecnoActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Listaproducto lista=new Listaproducto();
          
          lista.setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       Menu menu=new Menu();
          
          menu.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_agregarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarprodActionPerformed
        if(txt_descripcion.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_descripcion.requestFocus();
        }
        if(txt_precio2.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_precio2.requestFocus();
        }
        if(txt_stockmin.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_stockmin.requestFocus();
        }
        if(txt_stockact.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_stockact.requestFocus();
        }
        if(txt_objtecno.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_objtecno.requestFocus();
        }
        if(txt_codigo.getText() == null ? ("") != null : !txt_codigo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"No debe ingresar codigo para almacenar produtos");
        }
        else{

            Controladorproductos cp = new Controladorproductos();
            String descripcion = txt_descripcion.getText();
            String t_precio = txt_precio2.getText();
            String t_stockMinimo = txt_stockmin.getText();
            String t_stockActual = txt_stockact.getText();
            String tipoProducto = txt_objtecno.getText();

            int precio = Integer.parseInt(t_precio);
            int stockMinimo = Integer.parseInt(t_stockMinimo);
            int stockActual = Integer.parseInt(t_stockActual);

            Producto prod = new Producto(1, precio, stockMinimo, stockActual, t_stockMinimo, descripcion);

            cp.agregarProducto(prod);
            JOptionPane.showMessageDialog(this,"Producto "+tipoProducto+ " registrado");

        }

    }//GEN-LAST:event_btn_agregarprodActionPerformed

    private void btn_actualizarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarprodActionPerformed
        if(txt_descripcion.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_descripcion.requestFocus();
        }
        if(txt_precio2.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_precio2.requestFocus();
        }
        if(txt_stockmin.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_stockmin.requestFocus();
        }
        if(txt_stockact.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_stockact.requestFocus();
        }
        if(txt_objtecno.getText().equals("")){
            //||txt_precio.getText().equals("")||txt_stockMin.getText().equals("")||txt_stockActual.getText().equals("")||txt_tipoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"falta informacion");
            txt_objtecno.requestFocus();
        }
        else{
            String t_codigo = txt_codigo.getText();
            String descripcion = txt_descripcion.getText();
            String t_precio = txt_precio2.getText();
            String t_stockMinimo = txt_stockmin.getText();
            String t_stockActual = txt_stockact.getText();
            String tipoProducto = txt_objtecno.getText();

            int codigo = Integer.parseInt(t_codigo);
            int precio = Integer.parseInt(t_precio);
        int stockMinimo = Integer.parseInt(t_stockMinimo);
            int stockActual = Integer.parseInt(t_stockActual);

            Controladorproductos cp = new Controladorproductos();
             Producto prod = new Producto(codigo, precio, stockMinimo, stockActual, t_stockMinimo, descripcion);

            cp.modificarProducto(prod);
            JOptionPane.showMessageDialog(this,"Producto codigo:"+codigo+ " modificado");

        }
    }//GEN-LAST:event_btn_actualizarprodActionPerformed

    private void btn_eliminarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarprodActionPerformed
        if(txt_codigo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el codigo del producto");
            txt_codigo.requestFocus();

        }else{
            String t_codigo = txt_codigo.getText();
            int codigo = Integer.parseInt(t_codigo);
            Controladorproductos cp = new Controladorproductos();
            cp.eliminar(codigo);
            JOptionPane.showMessageDialog(this,"Producto borrado");
        }

    }//GEN-LAST:event_btn_eliminarprodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productovista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productovista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productovista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productovista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productovista().setVisible(true);
            }
        });
    }

         private void imagenicono(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarprod;
    private javax.swing.JButton btn_agregarprod;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminarprod;
    private javax.swing.JButton btn_realizarventa;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_codigoprod;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_iconocomputizado;
    private javax.swing.JLabel lbl_objtecn;
    private javax.swing.JLabel lbl_precioventa;
    private javax.swing.JLabel lbl_stockact;
    private javax.swing.JLabel lbl_stockmin;
    private javax.swing.JLabel lbl_tituloprod;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigoventa;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_objtecno;
    private javax.swing.JTextField txt_precio2;
    private javax.swing.JTextField txt_stockact;
    private javax.swing.JTextField txt_stockmin;
    // End of variables declaration//GEN-END:variables


class fondopanel extends JPanel
    {
        private Image fondoimagen;
        
        @Override
        public void paint(Graphics g)
        {
            fondoimagen = new ImageIcon(getClass().getResource("/imagen/fondoproducto.jpg")).getImage();
            
            g.drawImage(fondoimagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }


}
